### ISSUE TITLE
`import nbformat` gives: `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-python-kernel#120]
## Description

Building a fresh JupyterLite site with `nbformat` as a dependency gives the following issue:

 ![image](https://user-images.githubusercontent.com/591645/229123040-6a5c590e-31f2-4f0b-8548-708a01fdfcdc.png)

## Reproduce

1. Create `environment.yml` with the following content:

```yaml
name: test
channels:
- https://repo.mamba.pm/emscripten-forge
- https://repo.mamba.pm/conda-forge
dependencies:
- nbformat
```

2. Create a new virtual environment for the build
3. `python -m pip install jupyterlite-xeus-python`
4. `jupyter lite build`
5. `jupyter lite serve`
6. Open http://localhost:8000/_output/lab/index.html

## Expected behavior

It should be possible to import `nbformat`.

## Context

This came up when checking if `plotly` works with the xeus python kernel in JupyterLite:

```py
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title="Hello Figure")
fig.show()
```

![image](https://user-images.githubusercontent.com/591645/229124265-bf42b00e-aa4f-4c02-8058-2ffc664b83c3.png)
